# Contains the question bank with text and corresponding answers.
question_bank = [
    {"text": "The `print` function in Python outputs text to the console.", "answer": "True"},
    {"text": "In Python, `int` and `float` are types of string data.", "answer": "False"},
    {"text": "The keyword `def` is used to define a function in Python.", "answer": "True"},
    {"text": "A Python list is immutable.", "answer": "False"},
    {"text": "The `append` method adds an element to the end of a list in Python.", "answer": "True"},
    {"text": "Python uses curly braces '{}' to define code blocks.", "answer": "False"},
    {"text": "In Python, `==` is used to compare equality between two values.", "answer": "True"},
    {"text": "The `import` statement is used to include modules in a Python script.", "answer": "True"},
    {"text": "Python supports multiple inheritance.", "answer": "True"},
    {"text": "The `while` loop in Python executes a block of code as long as a condition is `False`.", "answer": "False"},
    {"text": "In Python, a tuple is a mutable sequence of elements.", "answer": "False"},
    {"text": "The `range` function generates a sequence of numbers.", "answer": "True"},
    {"text": "Python's `try` and `except` keywords are used for error handling.", "answer": "True"},
    {"text": "The `lambda` keyword is used to create anonymous functions in Python.", "answer": "True"},
    {"text": "In Python, `True` and `False` are considered as `int` values 1 and 0 respectively.", "answer": "True"},
    {"text": "The `len` function returns the length of a dictionary in Python.", "answer": "True"},
    {"text": "Python uses `==` to assign values to variables.", "answer": "False"},
    {"text": "A dictionary in Python is an ordered collection of key-value pairs.", "answer": "True"},
    {"text": "The `break` statement is used to exit a loop in Python.", "answer": "True"},
    {"text": "Python's `__init__` method is used for creating classes.", "answer": "False"},
    {"text": "The Great Wall of China is visible from space.", "answer": "False"},
    {"text": "Mount Everest is located in the Himalayas.", "answer": "True"},
    {"text": "Australia is both a country and a continent.", "answer": "True"},
    {"text": "The Nile River is the longest river in the world.", "answer": "True"},
    {"text": "Paris is the capital of Germany.", "answer": "False"},
    {"text": "The Sahara Desert is the largest hot desert in the world.", "answer": "True"},
    {"text": "The Amazon Rain forest is located in Africa.", "answer": "False"},
    {"text": "Antarctica is the driest continent on Earth.", "answer": "True"},
    {"text": "Tokyo is the capital of Japan.", "answer": "True"},
    {"text": "The Eiffel Tower is located in Rome.", "answer": "False"},
    {"text": "Brazil is the largest country in South America.", "answer": "True"},
    {"text": "The Dead Sea is known for its high salt content.", "answer": "True"},
    {"text": "Greenland is a continent.", "answer": "False"},
    {"text": "The city of Istanbul is located in two continents.", "answer": "True"},
    {"text": "The Statue of Liberty was a gift from France to the United States.", "answer": "True"},
    {"text": "Canada has the longest coastline of any country in the world.", "answer": "True"},
    {"text": "The official language of Brazil is Spanish.", "answer": "False"},
    {"text": "The Pacific Ocean is the smallest ocean on Earth.", "answer": "False"},
    {"text": "The city of Cairo is the capital of Egypt.", "answer": "True"},
    {"text": "The Great Barrier Reef is located off the coast of South Africa.", "answer": "False"},
    {"text": "Python supports both procedural and object-oriented programming.", "answer": "True"},
    {"text": "A `set` in Python is an ordered collection of unique elements.", "answer": "False"},
    {"text": "The `input` function is used to take input from the user in Python.", "answer": "True"},
    {"text": "A Python `dict` is an unordered collection of key-value pairs.", "answer": "True"},
    {"text": "The `continue` statement is used to skip the rest of the code inside a loop and jump to the next iteration.", "answer": "True"},
    {"text": "The `is` keyword in Python checks for equality of values.", "answer": "False"},
    {"text": "In Python, an `int` is a whole number without a decimal point.", "answer": "True"},
    {"text": "Python has a built-in `math` module that supports advanced mathematical operations.", "answer": "True"},
    {"text": "A Python function can return multiple values in the form of a list or tuple.", "answer": "True"},
    {"text": "The `elif` statement in Python is used for multiple conditions in an `if` block.", "answer": "True"},
    {"text": "Python has automatic garbage collection to manage memory.", "answer": "True"},
    {"text": "A Python list can store multiple data types (e.g., int, float, str).", "answer": "True"},
    {"text": "The `pass` statement in Python is used to skip the execution of a block of code.", "answer": "True"},
    {"text": "A Python function must have a return statement.", "answer": "False"},
    {"text": "The `try` block in Python is used to catch errors.", "answer": "False"},
    {"text": "The `for` loop in Python is used to iterate over a sequence of elements.", "answer": "True"},
    {"text": "The `or` operator in Python returns `True` only if both conditions are `True`.", "answer": "False"},
    {"text": "In Python, a dictionary's keys must be immutable (e.g., strings, tuples).", "answer": "True"},
    {"text": "A `tuple` in Python is mutable, unlike a list.", "answer": "False"},
    {"text": "In Python, `None` is used to represent the absence of a value or a null value.", "answer": "True"},
    {"text": "The `join` method in Python is used to concatenate elements of a list into a string.", "answer": "True"},
    {"text": "Python's `os` module can be used to interact with the operating system.", "answer": "True"},
    {"text": "In Python, an exception is handled using the `if-else` statement.", "answer": "False"},
    {"text": "The Eiffel Tower is located in Paris.", "answer": "True"},
    {"text": "Shakespeare wrote the play 'Hamlet'.", "answer": "True"},
    {"text": "The Earth's core is primarily composed of iron and nickel.", "answer": "True"},
    {"text": "The longest side of a right triangle is called the hypotenuse.", "answer": "True"},
    {"text": "The atomic number of oxygen is 8.", "answer": "True"},
    {"text": "Leonardo da Vinci was a famous scientist and painter.", "answer": "True"},
    {"text": "The human body has 8 ribs.", "answer": "False"},
    {"text": "The capital of Canada is Toronto.", "answer": "False"},
    {"text": "Mercury is the closest planet to the Sun.", "answer": "True"},
    {"text": "Venus is known as the 'Red Planet'.", "answer": "False"},
    {"text": "The speed of light is approximately 300,000 km/s.", "answer": "True"},
    {"text": "Albert Einstein developed the theory of relativity.", "answer": "True"},
    {"text": "Hawaii is the only U.S. state made up entirely of islands.", "answer": "True"},
    {"text": "The Amazon River is the longest river in the world.", "answer": "False"},
    {"text": "The Pyramids of Giza are located in Egypt.", "answer": "True"},
    {"text": "The Great Barrier Reef is located off the coast of Australia.", "answer": "True"},
    {"text": "Mount Kilimanjaro is located in South Africa.", "answer": "False"},
    {"text": "The largest continent by population is Asia.", "answer": "True"}
]
